#!/usr/bin/env bash

export HSA_OVERRIDE_GFX_VERSION=10.3.0
export HCC_AMDGPU_TARGET=gfx1030

echo "[ambiente] HSA_OVERRIDE_GFX_VERSION=$HSA_OVERRIDE_GFX_VERSION  HCC_AMDGPU_TARGET=$HCC_AMDGPU_TARGET"
